import os
from .check_type import KERNEL_VER_INPUT
from .definition_script import *
from .get_url import *

def buildmain():
    os.chdir('../../catalog')

    if os.path.exists(KERNEL_VER_INPUT):
        os.remove((KERNEL_VER_INPUT) + '/install.sh')
        os.remove((KERNEL_VER_INPUT) + '/README.md')
        os.rmdir(KERNEL_VER_INPUT)
        os.mkdir(KERNEL_VER_INPUT)
    else:
        os.mkdir(KERNEL_VER_INPUT)

    os.chdir(KERNEL_VER_INPUT)

    out = open("install.sh", 'w')
    head1 = lambda *x, **y: print(*x, **y, file=out) 
    head2 = lambda *x, **y: print(*x, **y, file=out) 
    head3 = lambda *x, **y: print(*x, **y, file=out) 
    head4 = lambda *x, **y: print(*x, **y, file=out) 
    head5 = lambda *x, **y: print(*x, **y, file=out) 
    head6 = lambda *x, **y: print(*x, **y, file=out) 
    head7 = lambda *x, **y: print(*x, **y, file=out) 
    head8 = lambda *x, **y: print(*x, **y, file=out) 
    head9 = lambda *x, **y: print(*x, **y, file=out) 
    head10 = lambda *x, **y: print(*x, **y, file=out) 
    head11 = lambda *x, **y: print(*x, **y, file=out) 
    head12 = lambda *x, **y: print(*x, **y, file=out) 
    head13 = lambda *x, **y: print(*x, **y, file=out) 
    head14 = lambda *x, **y: print(*x, **y, file=out) 
    head15 = lambda *x, **y: print(*x, **y, file=out) 
    head16 = lambda *x, **y: print(*x, **y, file=out) 
    head17 = lambda *x, **y: print(*x, **y, file=out) 
    head18 = lambda *x, **y: print(*x, **y, file=out) 
    head19 = lambda *x, **y: print(*x, **y, file=out) 
    head20 = lambda *x, **y: print(*x, **y, file=out) 
    head21 = lambda *x, **y: print(*x, **y, file=out) 
    head22 = lambda *x, **y: print(*x, **y, file=out) 
    head23 = lambda *x, **y: print(*x, **y, file=out) 
    head24 = lambda *x, **y: print(*x, **y, file=out) 
    head25 = lambda *x, **y: print(*x, **y, file=out) 
    head26 = lambda *x, **y: print(*x, **y, file=out) 
    head27 = lambda *x, **y: print(*x, **y, file=out) 
    head28 = lambda *x, **y: print(*x, **y, file=out) 
    head29 = lambda *x, **y: print(*x, **y, file=out) 
    head30 = lambda *x, **y: print(*x, **y, file=out) 
    head31 = lambda *x, **y: print(*x, **y, file=out) 
    head32 = lambda *x, **y: print(*x, **y, file=out) 
    head33 = lambda *x, **y: print(*x, **y, file=out) 
    head34 = lambda *x, **y: print(*x, **y, file=out) 
    head35 = lambda *x, **y: print(*x, **y, file=out) 
    head36 = lambda *x, **y: print(*x, **y, file=out) 
    head37 = lambda *x, **y: print(*x, **y, file=out) 
    head38 = lambda *x, **y: print(*x, **y, file=out) 
    head39 = lambda *x, **y: print(*x, **y, file=out) 
    head40 = lambda *x, **y: print(*x, **y, file=out) 
    head41 = lambda *x, **y: print(*x, **y, file=out) 
    head42 = lambda *x, **y: print(*x, **y, file=out) 
    head43 = lambda *x, **y: print(*x, **y, file=out) 
    head44 = lambda *x, **y: print(*x, **y, file=out) 
    head45 = lambda *x, **y: print(*x, **y, file=out) 
    head46 = lambda *x, **y: print(*x, **y, file=out) 
    head47 = lambda *x, **y: print(*x, **y, file=out) 
    head48 = lambda *x, **y: print(*x, **y, file=out) 
    head49 = lambda *x, **y: print(*x, **y, file=out) 
    head50 = lambda *x, **y: print(*x, **y, file=out) 
    head51 = lambda *x, **y: print(*x, **y, file=out) 
    head52 = lambda *x, **y: print(*x, **y, file=out) 
    head53 = lambda *x, **y: print(*x, **y, file=out) 

    op = open("README.md", 'w')
    read1 = lambda *x, **y: print(*x, **y, file=op) 
    read2 = lambda *x, **y: print(*x, **y, file=op) 
    read3 = lambda *x, **y: print(*x, **y, file=op) 
    read4 = lambda *x, **y: print(*x, **y, file=op) 
    read5 = lambda *x, **y: print(*x, **y, file=op) 
    read6 = lambda *x, **y: print(*x, **y, file=op) 
    read7 = lambda *x, **y: print(*x, **y, file=op) 
    read8 = lambda *x, **y: print(*x, **y, file=op) 
    read9 = lambda *x, **y: print(*x, **y, file=op) 
    read10 = lambda *x, **y: print(*x, **y, file=op) 
    read11 = lambda *x, **y: print(*x, **y, file=op) 
    read12 = lambda *x, **y: print(*x, **y, file=op) 
    read13 = lambda *x, **y: print(*x, **y, file=op) 
    read14 = lambda *x, **y: print(*x, **y, file=op) 
    read15 = lambda *x, **y: print(*x, **y, file=op) 
    read16 = lambda *x, **y: print(*x, **y, file=op) 
    read17 = lambda *x, **y: print(*x, **y, file=op) 
    read18 = lambda *x, **y: print(*x, **y, file=op) 
    read19 = lambda *x, **y: print(*x, **y, file=op) 
    read20 = lambda *x, **y: print(*x, **y, file=op) 
    read21 = lambda *x, **y: print(*x, **y, file=op) 
    read22 = lambda *x, **y: print(*x, **y, file=op) 
    read23 = lambda *x, **y: print(*x, **y, file=op) 
    read24 = lambda *x, **y: print(*x, **y, file=op) 
    read25 = lambda *x, **y: print(*x, **y, file=op) 

    head1(line1)
    head2(empty)
    head3(line3)
    head4(line4)
    head5(empty)
    head6(line6)
    head7(line7)
    head8(line8)
    head9(line9)
    head10(line10)
    head11(line11)
    head12((wget) + (empty1) + (wget1))
    head13((wget) + (empty1) + (wget2))
    head14((wget) + (empty1) + (wget3))
    head15((wget) + (empty1) + (wget4))
    head16(line16)
    head17(cd)
    head18(line18)
    head19(line19)
    head20(line20)
    head21(line21)
    head22(line22)
    head23(line23)
    head24(line24)
    head25(line25)
    head26(line26)
    head27(line27)
    head28(line10)
    head29(line11)
    head30((wget) + (empty1) + (wget5))
    head31((wget) + (empty1) + (wget6))
    head32((wget) + (empty1) + (wget7))
    head33(line16)
    head34(cd)
    head35(line18)
    head36(line25)
    head37(line26)
    head38(line38)
    head39(line39)
    head40(line40)
    head41(line41)
    head42(line42)
    head43(line43)
    head44(line19)
    head45(line20)
    head46(line46)
    head47(line22)
    head48(line48)
    head49(line24)
    head50(line25)
    head51(line26)
    head52(line52)
    head53(line53)
    read1(text1)
    read2(empty)
    read3(text3)
    read4(empty)
    read5(text5)
    read6(text6)
    read7(text7)
    read8(text8)
    read9(text9)
    read10(text6)
    read11(text11)
    read12(text8)
    read13(text13)
    read14(empty)
    read15(text5)
    read16(text6)
    read17(text17)
    read18(text8)
    read19(text9)
    read20(text6)
    read21(text11)
    read22(text8)
    read23(empty)
    read24(empty)
    read25(text25)

def buildrc():
    os.chdir('../../catalog')

    if os.path.exists(KERNEL_VER_INPUT):
        os.remove((KERNEL_VER_INPUT) + '/install.sh')
        os.remove((KERNEL_VER_INPUT) + '/README.md')
        os.rmdir(KERNEL_VER_INPUT)
        os.mkdir(KERNEL_VER_INPUT)
    else:
        os.mkdir(KERNEL_VER_INPUT)

    os.chdir(KERNEL_VER_INPUT)

    out = open("install.sh", 'w')
    head1 = lambda *x, **y: print(*x, **y, file=out) 
    head2 = lambda *x, **y: print(*x, **y, file=out) 
    head3 = lambda *x, **y: print(*x, **y, file=out) 
    head4 = lambda *x, **y: print(*x, **y, file=out) 
    head5 = lambda *x, **y: print(*x, **y, file=out) 
    head6 = lambda *x, **y: print(*x, **y, file=out) 
    head7 = lambda *x, **y: print(*x, **y, file=out) 
    head8 = lambda *x, **y: print(*x, **y, file=out) 
    head9 = lambda *x, **y: print(*x, **y, file=out) 
    head10 = lambda *x, **y: print(*x, **y, file=out) 
    head11 = lambda *x, **y: print(*x, **y, file=out) 
    head12 = lambda *x, **y: print(*x, **y, file=out) 
    head13 = lambda *x, **y: print(*x, **y, file=out) 
    head14 = lambda *x, **y: print(*x, **y, file=out) 
    head15 = lambda *x, **y: print(*x, **y, file=out) 
    head16 = lambda *x, **y: print(*x, **y, file=out) 
    head17 = lambda *x, **y: print(*x, **y, file=out) 
    head18 = lambda *x, **y: print(*x, **y, file=out) 
    head19 = lambda *x, **y: print(*x, **y, file=out) 
    head20 = lambda *x, **y: print(*x, **y, file=out) 
    head21 = lambda *x, **y: print(*x, **y, file=out) 
    head22 = lambda *x, **y: print(*x, **y, file=out) 
    head23 = lambda *x, **y: print(*x, **y, file=out) 
    head24 = lambda *x, **y: print(*x, **y, file=out) 
    head25 = lambda *x, **y: print(*x, **y, file=out) 
    head26 = lambda *x, **y: print(*x, **y, file=out) 
    head27 = lambda *x, **y: print(*x, **y, file=out) 
    head28 = lambda *x, **y: print(*x, **y, file=out) 
    head29 = lambda *x, **y: print(*x, **y, file=out) 
    head30 = lambda *x, **y: print(*x, **y, file=out) 
    head31 = lambda *x, **y: print(*x, **y, file=out) 
    head32 = lambda *x, **y: print(*x, **y, file=out) 
    head33 = lambda *x, **y: print(*x, **y, file=out) 
    head34 = lambda *x, **y: print(*x, **y, file=out) 
    head35 = lambda *x, **y: print(*x, **y, file=out) 
    head36 = lambda *x, **y: print(*x, **y, file=out) 
    head37 = lambda *x, **y: print(*x, **y, file=out) 
    head38 = lambda *x, **y: print(*x, **y, file=out) 
    head39 = lambda *x, **y: print(*x, **y, file=out) 
    head40 = lambda *x, **y: print(*x, **y, file=out) 
    head41 = lambda *x, **y: print(*x, **y, file=out) 
    head42 = lambda *x, **y: print(*x, **y, file=out) 
    head43 = lambda *x, **y: print(*x, **y, file=out) 
    head44 = lambda *x, **y: print(*x, **y, file=out) 
    head45 = lambda *x, **y: print(*x, **y, file=out) 
    head46 = lambda *x, **y: print(*x, **y, file=out) 
    head47 = lambda *x, **y: print(*x, **y, file=out) 
    head48 = lambda *x, **y: print(*x, **y, file=out) 
    head49 = lambda *x, **y: print(*x, **y, file=out) 
    head50 = lambda *x, **y: print(*x, **y, file=out) 
    head51 = lambda *x, **y: print(*x, **y, file=out) 
    head52 = lambda *x, **y: print(*x, **y, file=out) 
    head53 = lambda *x, **y: print(*x, **y, file=out) 
    head54 = lambda *x, **y: print(*x, **y, file=out) 

    op = open("README.md", 'w')
    read1 = lambda *x, **y: print(*x, **y, file=op) 
    read2 = lambda *x, **y: print(*x, **y, file=op) 
    read3 = lambda *x, **y: print(*x, **y, file=op) 
    read4 = lambda *x, **y: print(*x, **y, file=op) 
    read5 = lambda *x, **y: print(*x, **y, file=op) 
    read6 = lambda *x, **y: print(*x, **y, file=op) 
    read7 = lambda *x, **y: print(*x, **y, file=op) 
    read8 = lambda *x, **y: print(*x, **y, file=op) 
    read9 = lambda *x, **y: print(*x, **y, file=op) 
    read10 = lambda *x, **y: print(*x, **y, file=op) 
    read11 = lambda *x, **y: print(*x, **y, file=op) 
    read12 = lambda *x, **y: print(*x, **y, file=op) 
    read13 = lambda *x, **y: print(*x, **y, file=op) 
    read14 = lambda *x, **y: print(*x, **y, file=op) 
    read15 = lambda *x, **y: print(*x, **y, file=op) 
    read16 = lambda *x, **y: print(*x, **y, file=op) 
    read17 = lambda *x, **y: print(*x, **y, file=op) 
    read18 = lambda *x, **y: print(*x, **y, file=op) 
    read19 = lambda *x, **y: print(*x, **y, file=op) 
    read20 = lambda *x, **y: print(*x, **y, file=op) 
    read21 = lambda *x, **y: print(*x, **y, file=op) 
    read22 = lambda *x, **y: print(*x, **y, file=op) 
    read23 = lambda *x, **y: print(*x, **y, file=op) 
    read24 = lambda *x, **y: print(*x, **y, file=op) 
    read25 = lambda *x, **y: print(*x, **y, file=op) 

    head1(line1)
    head2(empty)
    head3(line3)
    head4(line3_1)
    head5(line4)
    head6(empty)
    head7(line6)
    head8(line7)
    head9(line8)
    head10(line9)
    head11(line10)
    head12(line11)
    head13((wget) + (empty1) + (wget1))
    head14((wget) + (empty1) + (wget2))
    head15((wget) + (empty1) + (wget3))
    head16((wget) + (empty1) + (wget4))
    head17(line16)
    head18(cd)
    head19(line18)
    head20(line19_1)
    head21(line20)
    head22(line21)
    head23(line22)
    head24(line23)
    head25(line24)
    head26(line25)
    head27(line26)
    head28(line27)
    head29(line10)
    head30(line11)
    head31((wget) + (empty1) + (wget5))
    head32((wget) + (empty1) + (wget6))
    head33((wget) + (empty1) + (wget7))
    head34(line16)
    head35(cd)
    head36(line18)
    head37(line25)
    head38(line26)
    head39(line38)
    head40(line39)
    head41(line40)
    head42(line41_1)
    head43(line42_1)
    head44(line43_1)
    head45(line19_1)
    head46(line20)
    head47(line46)
    head48(line22)
    head49(line48)
    head50(line24)
    head51(line25)
    head52(line26)
    head53(line52)
    head54(line53)

    read1(text1)
    read2(empty)
    read3(text3)
    read4(empty)
    read5(text5)
    read6(text6)
    read7(text7)
    read8(text8)
    read9(text9)
    read10(text6)
    read11(text11)
    read12(text8)
    read13(text13)
    read14(empty)
    read15(text5)
    read16(text6)
    read17(text17)
    read18(text8)
    read19(text9)
    read20(text6)
    read21(text11)
    read22(text8)
    read23(empty)
    read24(empty)
    read25(text25)

from .definition_readme import *

def buildreadme():
    os.chdir('../../')
    os.system('rm readme.md')

    out = open("readme.md", 'w')
    headr1 = lambda *x, **y: print(*x, **y, file=out) 
    headr2 = lambda *x, **y: print(*x, **y, file=out) 
    headr3 = lambda *x, **y: print(*x, **y, file=out) 
    headr4 = lambda *x, **y: print(*x, **y, file=out) 
    headr5 = lambda *x, **y: print(*x, **y, file=out) 
    headr6 = lambda *x, **y: print(*x, **y, file=out) 
    headr7 = lambda *x, **y: print(*x, **y, file=out) 
    headr8 = lambda *x, **y: print(*x, **y, file=out) 
    headr9 = lambda *x, **y: print(*x, **y, file=out) 
    headr10 = lambda *x, **y: print(*x, **y, file=out) 
    headr11 = lambda *x, **y: print(*x, **y, file=out) 
    headr12 = lambda *x, **y: print(*x, **y, file=out) 
    headr13 = lambda *x, **y: print(*x, **y, file=out) 
    headr14 = lambda *x, **y: print(*x, **y, file=out) 
    headr15 = lambda *x, **y: print(*x, **y, file=out) 
    headr16 = lambda *x, **y: print(*x, **y, file=out) 
    headr17 = lambda *x, **y: print(*x, **y, file=out) 
    headr18 = lambda *x, **y: print(*x, **y, file=out) 
    headr19 = lambda *x, **y: print(*x, **y, file=out) 
    headr20 = lambda *x, **y: print(*x, **y, file=out) 
    headr21 = lambda *x, **y: print(*x, **y, file=out) 
    headr22 = lambda *x, **y: print(*x, **y, file=out) 
    headr23 = lambda *x, **y: print(*x, **y, file=out) 
    headr24 = lambda *x, **y: print(*x, **y, file=out) 
    headr25 = lambda *x, **y: print(*x, **y, file=out) 
    headr26 = lambda *x, **y: print(*x, **y, file=out) 
    headr27 = lambda *x, **y: print(*x, **y, file=out) 
    headr28 = lambda *x, **y: print(*x, **y, file=out) 
    headr29 = lambda *x, **y: print(*x, **y, file=out) 
    headr30 = lambda *x, **y: print(*x, **y, file=out) 
    headr31 = lambda *x, **y: print(*x, **y, file=out) 
    headr32 = lambda *x, **y: print(*x, **y, file=out) 
    headr33 = lambda *x, **y: print(*x, **y, file=out) 
    headr34 = lambda *x, **y: print(*x, **y, file=out) 
    headr35 = lambda *x, **y: print(*x, **y, file=out) 
    headr36 = lambda *x, **y: print(*x, **y, file=out) 
    headr37 = lambda *x, **y: print(*x, **y, file=out) 
    headr38 = lambda *x, **y: print(*x, **y, file=out) 
    headr39 = lambda *x, **y: print(*x, **y, file=out) 
    headr40 = lambda *x, **y: print(*x, **y, file=out) 
    headr41 = lambda *x, **y: print(*x, **y, file=out) 
    headr42 = lambda *x, **y: print(*x, **y, file=out) 
    headr43 = lambda *x, **y: print(*x, **y, file=out) 
    headr44 = lambda *x, **y: print(*x, **y, file=out) 
    headr45 = lambda *x, **y: print(*x, **y, file=out) 
    headr46 = lambda *x, **y: print(*x, **y, file=out) 
    headr47 = lambda *x, **y: print(*x, **y, file=out) 
    headr48 = lambda *x, **y: print(*x, **y, file=out) 
    headr49 = lambda *x, **y: print(*x, **y, file=out) 
    headr50 = lambda *x, **y: print(*x, **y, file=out) 
    headr51 = lambda *x, **y: print(*x, **y, file=out) 
    headr52 = lambda *x, **y: print(*x, **y, file=out) 
    headr53 = lambda *x, **y: print(*x, **y, file=out) 
    headr54 = lambda *x, **y: print(*x, **y, file=out) 
    headr55 = lambda *x, **y: print(*x, **y, file=out) 
    headr56 = lambda *x, **y: print(*x, **y, file=out) 
    headr57 = lambda *x, **y: print(*x, **y, file=out) 
    headr58 = lambda *x, **y: print(*x, **y, file=out) 
    headr59 = lambda *x, **y: print(*x, **y, file=out) 
    headr60 = lambda *x, **y: print(*x, **y, file=out) 
    headr61 = lambda *x, **y: print(*x, **y, file=out) 
    headr62 = lambda *x, **y: print(*x, **y, file=out) 
    headr63 = lambda *x, **y: print(*x, **y, file=out) 
    headr64 = lambda *x, **y: print(*x, **y, file=out) 
    headr65 = lambda *x, **y: print(*x, **y, file=out) 
    headr66 = lambda *x, **y: print(*x, **y, file=out) 
    headr67 = lambda *x, **y: print(*x, **y, file=out) 
    headr68 = lambda *x, **y: print(*x, **y, file=out) 
    headr69 = lambda *x, **y: print(*x, **y, file=out) 
    headr70 = lambda *x, **y: print(*x, **y, file=out) 
    headr71 = lambda *x, **y: print(*x, **y, file=out) 
    headr72 = lambda *x, **y: print(*x, **y, file=out) 
    headr73 = lambda *x, **y: print(*x, **y, file=out) 
    headr74 = lambda *x, **y: print(*x, **y, file=out) 

    headr1(l1)
    headr2(l2)
    headr3(l3)
    headr4(l4)
    headr5(l5)
    headr6(l6)
    headr7(l7)
    headr8(l8)
    headr9(l9)
    headr10(l10)
    headr11(l11)
    headr12(l12)
    headr13(l13)
    headr14(l14)
    headr15(l15)
    headr16(l16)
    headr17(l17)
    headr18(l18)
    headr19(l19)
    headr20(l20)
    headr21(l21)
    headr22(l22)
    headr23(l23)
    headr24(l24)
    headr25(l25)
    headr26(l26)
    headr27(l27)
    headr28(l28)
    headr29(l29)
    headr30(l30)
    headr31(l31)
    headr32(l32)
    headr33(l33)
    headr34(l34)
    headr35(l35)
    headr36(l36)
    headr37(l37)
    headr38(l38)
    headr39(l39)
    headr40(l40)
    headr41(l41)
    headr42(l42)
    headr43(l43)
    headr44(l44)
    headr45(l45)
    headr46(l46)
    headr47(l47)
    headr48(l48)
    headr49(l49)
    headr50(l50)
    headr51(l51)
    headr52(l52)
    headr53(l53)
    headr54(l54)
    headr55(l55)
    headr56(l56)
    headr57(l57)
    headr58(l58)
    headr59(l59)
    headr60(l60)
    headr61(l61)
    headr62(l62)
    headr63(l63)
    headr64(l64)
    headr65(l65)
    headr66(l66)
    headr67(l67)
    headr68(l68)
    headr69(l69)
    headr70(l70)
    headr71(l71)
    headr72(l72)
    headr73(l73)
    headr74(l74)